// This populates our dropdown menu's in case the api is not connected

export const fallbackFilterOptions = {
  activity: ["architecture", "art", "beach", "history"],
  cost: ["cheap", "expensive", "medium"],
  month: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  vibe: [
    "Cultural Roots",
    "Frugal Adventure",
    "Gastronomic Journey",
    "Pure Relaxation",
    "Rustic Wilderness",
    "Sun & Sand",
    "Urban Explorer",
  ],
  weather: ["Hot", "Mild", "Cold"],
};

export const fallbackDestinations = [
  {
    activity_name: "Visit the Van Gogh Museum",
    activity_type: "art",
    avg_temp_c: 18.5,
    cost: "expensive",
    country: "Netherlands",
    destination: "Amsterdam",
    match_count: 0,
    rainfall_mm: 75,
    selected_filter_count: 0,
    vibes: ["Pure Relaxation", "Urban Explorer"],
    weather_band: "Mild",
  },
  {
    activity_name: "Visit the Acropolis",
    activity_type: "history",
    avg_temp_c: 28.5,
    cost: "cheap",
    country: "Greece",
    destination: "Athens",
    match_count: 0,
    rainfall_mm: 6,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Frugal Adventure"],
    weather_band: "Hot",
  },
  {
    activity_name: "Visit Barceloneta Beach",
    activity_type: "beach",
    avg_temp_c: 26,
    cost: "medium",
    country: "Spain",
    destination: "Barcelona",
    match_count: 0,
    rainfall_mm: 20,
    selected_filter_count: 0,
    vibes: ["Gastronomic Journey", "Sun & Sand"],
    weather_band: "Hot",
  },
  {
    activity_name: "See the Berlin Wall Memorial",
    activity_type: "history",
    avg_temp_c: 19,
    cost: "medium",
    country: "Germany",
    destination: "Berlin",
    match_count: 0,
    rainfall_mm: 70,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Urban Explorer"],
    weather_band: "Mild",
  },
  {
    activity_name: "Walk along the Dubrovnik coastline",
    activity_type: "beach",
    avg_temp_c: 26.5,
    cost: "medium",
    country: "Croatia",
    destination: "Dubrovnik",
    match_count: 0,
    rainfall_mm: 26,
    selected_filter_count: 0,
    vibes: ["Pure Relaxation", "Sun & Sand"],
    weather_band: "Hot",
  },
  {
    activity_name: "Explore Edinburgh Castle",
    activity_type: "history",
    avg_temp_c: 15.5,
    cost: "medium",
    country: "United Kingdom",
    destination: "Edinburgh",
    match_count: 0,
    rainfall_mm: 65,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Rustic Wilderness"],
    weather_band: "Mild",
  },
  {
    activity_name: "Visit Hagia Sophia",
    activity_type: "architecture",
    avg_temp_c: 25.5,
    cost: "cheap",
    country: "Turkey",
    destination: "Istanbul",
    match_count: 0,
    rainfall_mm: 25,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Gastronomic Journey"],
    weather_band: "Hot",
  },
  {
    activity_name: "Explore Alfama and historic Lisbon",
    activity_type: "history",
    avg_temp_c: 24.5,
    cost: "medium",
    country: "Portugal",
    destination: "Lisbon",
    match_count: 0,
    rainfall_mm: 6,
    selected_filter_count: 0,
    vibes: ["Gastronomic Journey", "Urban Explorer"],
    weather_band: "Mild",
  },
  {
    activity_name: "Visit the Louvre Museum",
    activity_type: "art",
    avg_temp_c: 21,
    cost: "expensive",
    country: "France",
    destination: "Paris",
    match_count: 0,
    rainfall_mm: 55,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Gastronomic Journey"],
    weather_band: "Mild",
  },
  {
    activity_name: "Visit the Colosseum",
    activity_type: "history",
    avg_temp_c: 27,
    cost: "medium",
    country: "Italy",
    destination: "Rome",
    match_count: 0,
    rainfall_mm: 15,
    selected_filter_count: 0,
    vibes: ["Cultural Roots", "Gastronomic Journey"],
    weather_band: "Hot",
  },
];
